apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      ci: true
  template:
    metadata:
      labels:
        app: helloworld
        ci: true
    spec:
      containers:
      - name: helloworld
        image: registry.harbor:5000/library/helloworld
